config/routes.rb
Rails.application.routes.draw do

  #SESSIONS

  get '/login', to: 'sessions#new'
  
  post '/login', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  #STATIC PAGES

  root 'static_pages#home'

  get 'static_pages/home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  #USERS

  get '/signup', to: 'users#new'
  
  resources :users

  #MICROPOSTS

  resources :microposts, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user

  default_scope -> { order(created_at: :desc) }

  validates :content, presence: true, length: { maximum: 280 }
  validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  #VALIDATIONS
  valid_email_regexp = /\A[\w+\-._]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, uniqueness: { case_sensitive: false }, presence: true, length: { maximum: 100 }, format: { with: valid_email_regexp }
  
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true, length: { minimum: 6 }

  #RELATIONS
  has_many :microposts, dependent: :destroy

  #FIELDS
  attr_accessor :remember_token

  #METHODS
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #Returns a random token
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def timeline
  	Micropost.where("user_id = ?", id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include  SessionsHelper
  protect_from_forgery with: :exception

  private
    def logged_in_user
    unless logged_in?
      flash[:danger] = 'Please login'
      redirect_to login_url
    end
  end
  
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  
  def create
  	@micropost = current_user.microposts.build(micropost_params)
  	if @micropost.save
  	  flash[:success] = "Micropost successfully created"
  	  redirect_to root_url
  	else
  	  render root_url
  	end
  end

  def destroy
  	
  end

  private
  def micropost_params
  	params.require(:micropost).permit(:content)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
  	user = User.find_by(email: params[:session][:email])

  	if user && user.authenticate(params[:session][:password])
      log_in user
      params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      redirect_to user
  	else
  	  flash.now[:danger] = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
  	log_out if logged_in?
  	redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
      @micropost = current_user.microposts.build if logged_in?
  	  @timeline_items = current_user.timeline.paginate(page: params[:page])
  	end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      flash[:success] = "Welcome to Micropost app"
      redirect_to @user
    else 
      render 'new'
  	end
  end

  def edit
    @user = User.find_by(id: params[:id])
  end

  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = 'Your info was updated'
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  #helper methods, only used in this controller
  private
  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user? @user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
  	base_title = "MicropostApp"
  	if page_title.empty?
  	  base_title
  	else
  		base_title + " | " + page_title
  	end
  end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user) 
  	session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
  	if (user_id = session[:user_id])
  	  @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
  	end
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
  	!current_user.nil?
  end

  def log_out
    forget current_user
  	session.delete(:user_id)
  	@current_user = nil
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The Ruby on Rails Course by thincode
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "sample app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Contact", contact_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
      
      <%= render 'layouts/footer' %>

      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
	  Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
	  <div class="alert alert.danger">
	    The form contains
	    <%= pluralize(object.errors.count, "error") %>
	  </div>
		<ul>
		  <% object.errors.full_messages.each do |message| %>
		    <li><%= message %>
		  <% end %>
		</ul>
    </div>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
  	<%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_timeline.html.erb
<% if @timeline_items.any? %>
  <ol class="microposts">
  	<%= render @timeline_items %>
  </ol>
  <%= will_paginate @timeline_items %>
<% end %>

app/views/shared/_user_info.html.erb
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Esta págin fue desarrollada por mí</h1>
<p>Más información en google.com</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>Para más información escriba a wey@pri.com</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>Puedes encontrar ayuda de esta applicacion en el repo de bitbucket</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<% if logged_in? %>
  <div class="row">
  	<aside class="col-md-4">
  	  <section class="user_info">
  	    <%= render 'shared/user_info' %>
  	  </section>
  	  <section class="micropost_form">
  	  	<%= render 'shared/micropost_form' %>
  	  </section>
  	</aside>
  	<div class="col-md-8">
  	  <h3>Micropost timeline</h3>
  	  <%= render 'shared/timeline' %>
  	</div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Micropost App</h1>

    <h2>
      Esta es la pagina del curso de Ruby on Rails de thincode
      <br />Ruby on Rails Tutorial
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages", object: User.new %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit my info') %>
<% provide(:button_text, 'Save') %>
<h1>Edit your info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>
<ul class="users">
	<% @users.each do |user| %>
	  <li>
	  	<%= link_to user.name, user %>
	  </li>
	<% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Create your account') %>
<% provide(:button_text, 'Create my account') %>
<h1>Enter your info</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
  	<section class="user_info">
  	  <h1>
  	  	<%= @user.name %>,
  	  	<%= @user.email %>
  	  </h1>
  	</section>
  </aside>
  <div class="col-md-8">
  	<% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
      	<% @microposts.each do |micropost| %>
      	<%= render micropost %>
      	<% end %>
      </ol>
      <%= will_paginate @microposts %>
  	<% end %>
  </div>
</div>